# Generated by Django 2.0.7 on 2018-07-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='password2',
        ),
    ]
