# Generated by Django 2.0.7 on 2018-07-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0002_remove_usuarios_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
