# Generated by Django 2.0.7 on 2018-07-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0004_auto_20180715_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='ud',
        ),
    ]
