# Generated by Django 2.0.7 on 2018-07-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0005_remove_cursos_ud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='anho',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='semestres',
        ),
    ]
