# Generated by Django 2.0.7 on 2018-07-23 03:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0006_auto_20180722_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='anho',
            field=models.DateField(db_column='Anho', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='departamento',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='Main_DDAF.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='semestres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Main_DDAF.Semestres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursos',
            name='ud',
            field=models.CharField(db_column='UD', default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
