# Generated by Django 2.0.7 on 2018-07-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0007_auto_20180722_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosDDAF',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('horario', models.CharField(db_column='Horario', max_length=32)),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
                ('capacidad', models.IntegerField(db_column='Capacidad')),
            ],
            options={
                'db_table': 'cursos_ddaf',
                'managed': True,
            },
        ),
    ]
