# Generated by Django 2.0.7 on 2018-07-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0009_auto_20180723_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'managed': True},
        ),
    ]
