# Generated by Django 2.0.7 on 2018-07-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0010_auto_20180723_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosddaf',
            options={},
        ),
        migrations.RemoveField(
            model_name='cursosddaf',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='cursosddaf',
            name='tipo',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursosddaf',
            name='horario',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cursosddaf',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterModelTable(
            name='cursosddaf',
            table=None,
        ),
    ]
