# Generated by Django 2.0.7 on 2018-07-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0011_auto_20180729_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursosDDAF',
        ),
    ]
