# Generated by Django 2.0.7 on 2018-07-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0012_delete_cursosddaf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosDDAF',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=64)),
                ('tipo', models.CharField(db_column='tipo', max_length=64)),
                ('horario', models.CharField(db_column='horario', max_length=32)),
            ],
            options={
                'db_table': 'cursos_ddaf',
                'managed': True,
            },
        ),
    ]
