# Generated by Django 2.0.7 on 2018-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0014_auto_20180730_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosddaf',
            name='capacidad',
            field=models.IntegerField(db_column='capacidad', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursosddaf',
            name='días',
            field=models.CharField(db_column='dias', max_length=32),
        ),
    ]
