# Generated by Django 2.0.7 on 2018-08-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0015_auto_20180730_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos_Alumno',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('curso', models.CharField(db_column='nombre_curso', max_length=64)),
                ('usuario', models.CharField(db_column='usuario', max_length=64)),
            ],
            options={
                'db_table': 'curso_alumno',
                'managed': True,
            },
        ),
    ]
