# Generated by Django 2.0.7 on 2018-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0016_cursos_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(choices=[('CARLOS', 'CARLOS'), ('ADRIANA', 'ADRIANA')], max_length=100)),
            ],
        ),
    ]
