# Generated by Django 2.0.7 on 2018-08-16 15:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main_DDAF', '0017_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='nombre_alumno',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CARLOS', 'CARLOS'), ('ADRIANA', 'ADRIANA')], max_length=14),
        ),
    ]
